"""

The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

"""


import math


def generate_nth_triangle(n):
	ans = 0

	for i in range(1, n + 1):
		ans += i

	return ans




def number_divisors(n):
	numbers = 0

	sqrt_n = math.floor(math.sqrt(n))


	for i in range(1, sqrt_n + 1):
		if n % i == 0:
			numbers += 2

	if sqrt_n**2 == n:
		numbers -= 1



	return numbers

def compute(num_divisors):
	
	i = 2

	triangle = 1

	while True:
		
		triangle += i
		num_div = number_divisors(triangle)

		print("iteration: "+str(i)+".....num_div: "+str(num_div))

		if num_div > num_divisors:
			return triangle
			
		i += 1


if __name__ == '__main__':
	print(compute(500))